### ISSUE TITLE
Hey there,I would like to collaborate with you.

### ISSUE THREAD

**Issue by starfowl** [starfowl/python-random-quote#6]
Hey there,I would like to collaborate with you.

_Originally posted by @rahulsust in https://github.com/starfowl/python-random-quote/issues/4#issuecomment-881979581_

**Comment by starfowl** [comment]
I hope you can see this @rahulsust
I would love to collab with you as I am just beginning! 
I think you saw me because I looked at you, I didn't know you could see that oops.
What do you want to do?

**Comment by rahulsust** [comment]
Yes I can see that 😄 @starfowl.
You know, I am also a beginner. I was searching someone like you. I first thing we can do is to learn together. Then do some projects. Now let me know, How do you think?

**Comment by m-a-g-g** [comment]
Guys you have created an issue and there is nothing found in the issue to solve. Please close this issue.

**Comment by starfowl** [comment]
@rahulsust I think that's an great idea! Shall I open a project and then we discuss what we want to do?

How do I think...
Hmm I think that we can help each other by giving feedback on what we are learning first, then maybe make up ideas and see the what we can do? 

If we struggle we can comment with a tag, and if we know something to do we react in the project?

**Comment by starfowl** [comment]
> Guys you have created an issue and there is nothing found in the issue to solve. Please close this issue.

Sorry agarwal!
